### ISSUE TITLE
lookup-nearest gives too wild guesses

### ISSUE THREAD

**Issue by heikoklein** [metno/geocoder_reverse_natural_earth#3]
Results from lookup-nearest are sometimes too wild guesses, e.g. 
```
print(geo.lookup_nearest(45.31390, 12.508300)["ISO_A2_EH"])
NO
```
though this station is in coastal waters of Venice/IT.

Originally reported by @jgriesfeller

**Comment by lewisblake** [comment]
Related PR: https://github.com/metno/pyaerocom/pull/978

A fix for this should include a test like the one failing in that PR.
